merge :: (#10) MainView-Publishing
GRAM-DSM/KillerGram-Android-V1.kt pull request #11
Opened 2024-10-13 09:22 UTC by uson1004

homeView 제작, 캘린더 기능, 운동 리스트(recyclerView를 곁들인), view 선택 상태처리(enterSkills) 등을 구현하였습니다.
![image](https://github.com/user-attachments/assets/5c9a2a2c-b8df-4a39-8673-1b85e6a6441b)

2024-10-14 04:52 UTC, Tmdhoon2 requested changes

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/SplashActivity.kt
> +    }
이 부분은 제안드리는건데, 지금 각 액티비티마다 onClick을 처리하는 함수와 binding 필드가 모두 존재하는 것 같아요
공통적인 부분을 추상화 시키면 코드가 좀 더 깔끔해질 것 같아요

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/enterinfo/enterSkill/EnterSkillsViewModel.kt
> +//
주석은 필요없으면 지우셔도 될 것 같아요!

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/home/HomeActivity.kt
> +            }
밑에 when문하고 동일한 로직이네요 공통화 시켜서 사용할 수 있을 것 같습니다.

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/home/HomeViewModelFactory.kt
HomeViewModel 생성자에 아무 값도 없어서 당장은 필요없을 것 같은데 확장성 고려해서 만들어두신 건가요??

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +    }
이건 어떤 역할을 하는 함수인가요??

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/recyclerView/dum.java
이건 어떤 역할을 하는 클래스인가요??

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/res/drawable/button_selected.xml
> +            <stroke android:width="4px"
픽셀로 주신 이유가 있을까요??

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/res/drawable/calender_text_color.xml
혹시 이 파일 없이는 색상 적용이 불가능한가요??

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/res/layout/activity_email_validation.xml
> +            android:id="@+id/glBottom"
아이디는 스네이크 케이스로 통일하는게 일관성 있고 좋을 것 같습니다!

2024-10-14 04:52 UTC, Tmdhoon2 commented on app/src/main/res/layout/activity_email_validation.xml
> +            android:id="@+id/glBottom"
이건 다른 파일에 있는 부분도 마찬가지입니다!

2024-10-14 09:06 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/SplashActivity.kt
> +    }
넵

2024-10-14 09:07 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/enterinfo/enterSkill/EnterSkillsViewModel.kt
> +//
넵

2024-10-14 09:13 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +    }
SimpleDateFormat을 이용하여 정해진 문법에 맞게 날짜를 입력받아 포맷팅 하려고 제작했습니다. 지금은 쓰이지 않아 제거하겠습니당

2024-10-14 09:15 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/recyclerView/dum.java
하위 레벨의 폴더가 파일 없이 존재하게 되면 상위 폴더와 겹쳐져서 임의의 파일을 생성해두었습니다. 다른 파일로 대체할 예정입니다!

2024-10-14 09:16 UTC, uson1004 commented on app/src/main/res/drawable/button_selected.xml
> +            <stroke android:width="4px"
지적 감사합니다. dp로 수정했습니다

2024-10-14 09:16 UTC, uson1004 commented on app/src/main/res/drawable/calender_text_color.xml
이해했습니다 수정하겠습니당

2024-10-14 09:18 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/home/HomeViewModelFactory.kt
HomeViewModel에는 LiveData가 있는 것으로 알고있는데 생성자에 값이 없다는 말씀이 무엇을 의미하시는 지 이해를 못하였습니다ㅠ

2024-10-14 23:55 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/home/HomeViewModelFactory.kt
<img width="255" alt="스크린샷 2024-10-15 오전 8 47 28" src="https://github.com/user-attachments/assets/c00d3519-226a-4197-80f6-76086db633c4">

HomeViewModel에는 생성자에 값이 없어요.
코틀린에서 생성자는 클래스 이름 옆에 열린 ()를 의미합니다.
생성자에 값이 없다는건 객체 생성 시 전달하는 값이 없다는 의미입니다.
근데 뷰모델 팩토리는 보통 뷰모델 생성자에 값을 넣어주기 위해 사용합니다.
그래서 말씀드린겁니다!

2024-10-15 07:39 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/home/HomeViewModelFactory.kt
아하 네 맞습니다 🚀

2024-10-15 07:40 UTC, uson1004 commented on app/src/main/res/layout/activity_email_validation.xml
> +            android:id="@+id/glBottom"
넵 수정했습니다

2024-10-15 12:25 UTC, merged