merge :: (#8) Modify View Style #6
GRAM-DSM/KillerGram-Android-V1.kt pull request #9
Opened 2024-09-23 12:46 UTC by uson1004

inputtextlayout이 존재하는 edittext에서 이메일 오류, 비밀번호 오류 error 코드를 정의해주었습니다.

2024-09-23 23:44 UTC, Tmdhoon2 requested changes

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/enterinfo/EnterGenderActivity.kt
> +        binding.ImVLeftArrow.setOnClickListener(this)
자자 이미지뷰는 보통
`img_left_arrow` 이렇게 네이밍을 합니다.
네이밍 규칙에 맞게 수정해봅시당

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/enterinfo/EnterGenderActivity.kt
> +        binding.ImVLeftArrow.setOnClickListener(this)
여기가 수정되면 나머지도 다 수정되겠죠??

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +        binding.TIEEmail.addTextChangedListener(object : TextWatcher {
여기도 TextInputEditText의 아이디 인것 같은데, 아이디는 xml에서는 스네이크 케이스, 자바 파일에서는 카멜 케이스를 지키는게 좋아욤

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +            }
여기도 코틀린을 더 잘 활용해보면 중복되는 코드를 줄일 수 있을 것 같아용

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +    }
함수 분할 굉장히 좋습니당 👍

2024-09-23 23:44 UTC, Tmdhoon2 commented on app/src/main/java/com/example/killergram_android_v1/feature/signup/InputEmailActivity.kt
> +    }
이 함수는 다른 파일에 있는 함수를 재활용할 수 있을 것 같아요!

2024-09-24 12:23 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/enterinfo/EnterGenderActivity.kt
> +        binding.ImVLeftArrow.setOnClickListener(this)
넵 수정하겠습니다

2024-09-24 12:24 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +        binding.TIEEmail.addTextChangedListener(object : TextWatcher {
"TieEmail" 이런식으로 작성하겠습니닷

2024-09-24 12:24 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +            }
적용해보겠습니다

2024-09-24 12:24 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/login/LoginActivity.kt
> +    }
감사합니다

2024-09-24 12:24 UTC, uson1004 commented on app/src/main/java/com/example/killergram_android_v1/feature/signup/InputEmailActivity.kt
> +    }
적용해보겠습니다!

2024-09-27 05:34 UTC, uson1004 commented
수정완료

2024-09-29 14:32 UTC, merged